language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy python-scipy python-matplotlib cython
  - sudo apt-get install -qq python-nose
install:
  - python setup.py build_ext --inplace
  - python setup.py build
  - sudo python setup.py install
script:
  - python integration_tests/runtest.py
  - diff -r test_results/ integration_tests/stored_results/
  - nosetests -v helixmc
