language: python
python:
  - 2.7
install:
  - pip install nose
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install Cython
script:
  - python setup.py build
  - sudo python setup.py install
